import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
        style ={{
          width : "100%",
          background : "teal",
          fontSize : "50px",
          display : "flex",
          alignItems : "centre ",
          justifyContent : "centre ",
        }}
        >
          <Link style = { {margin : " 100 px "} } href= {"/"} >  Home </Link>
          <Link style = { {margin : " 100 px "} } href= {"/posts"} >  Posts </Link>
          <Link style = { {margin : " 100 px "} } href= {"/article"} >  Article </Link>
          <Link style = { {margin : " 100 px "} } href= {"/comment"} >  Comments</Link>
        </nav>
        {children}</body>
    </html>
  );
}
